# Server Port
server.port=8080

# Upload settings
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# PostgreSQL Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/banking_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Cache Configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Application constants
gemini.model=gemini-2.5-flash
gemini.api.key=AIzaSyCRMegyJSJUMMHip-t3Rv9jB3uiDOYoa84
jwt.secret=9a6767667174372d392f39703373767c7e2b7b252d3d3a3f4b4d5b5d6e6f777e
jwt.expiration=864000000

# Logging Configuration
logging.level.com.example.banking=INFO
